<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2008-2015 Sonatype, Inc. and others
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License 2.0
  which accompanies this distribution, and is available at
  https://www.eclipse.org/legal/epl-2.0/

  SPDX-License-Identifier: EPL-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.m2e.wtp</groupId>
		<artifactId>org.eclipse.m2e.wtp.parent</artifactId>
		<version>1.6.2-SNAPSHOT</version>
		<relativePath>../..</relativePath>
	</parent>

	<artifactId>org.eclipse.m2e.wtp.promotion</artifactId>

	<packaging>pom</packaging>

	<name>M2E-WTP :: Promotion</name>

	<properties>
		<eclipse.repo>https://download.eclipse.org/releases/latest</eclipse.repo>
		<justj.tools.repo>https://download.eclipse.org/justj/tools/updates/nightly/latest</justj.tools.repo>
		<org.eclipse.storage.user>genie.m2e</org.eclipse.storage.user>
		<org.eclipse.justj.p2.manager.remote>${org.eclipse.storage.user}@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/technology/m2e/m2e-wtp</org.eclipse.justj.p2.manager.remote>
		<org.eclipse.justj.p2.manager.relative>updates</org.eclipse.justj.p2.manager.relative>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<org.eclipse.justj.p2.manager.build.url>http://www.example.com/</org.eclipse.justj.p2.manager.build.url>
		<build.type>nightly</build.type>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho.extras</groupId>
				<artifactId>tycho-p2-extras-plugin</artifactId>
				<version>${tycho-version}</version>
				<executions>
					<execution>
						<id>promote-build</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>p2-manager</goal>
						</goals>
						<configuration>
							<retain>5</retain>
							<label>m2e Web Tools Platform Integration</label>
							<buildUrl>${org.eclipse.justj.p2.manager.build.url}</buildUrl>
							<remote>${org.eclipse.justj.p2.manager.remote}</remote>
							<root>${project.basedir}/m2e-wtp</root>
							<relative>${org.eclipse.justj.p2.manager.relative}</relative>
							<versionIU>org.eclipse.m2e.wtp.feature.feature.group</versionIU>
							<commit>https://github.com/eclipse-m2e/m2e-wtp/commit/${git.commit}</commit>
							<targetUrl>https://download.eclipse.org/technology/m2e/m2e-wtp</targetUrl>
							<promote>${project.basedir}/../target/repository</promote>
							<timestamp>${build.timestamp}</timestamp>
							<type>${build.type}</type>
							<breadcrumbs>
								<breadcrumb>m2e&#xA0;WTP https://projects.eclipse.org/projects/technology.m2e</breadcrumb>
							</breadcrumbs>
							<mappings>
								<mapping> m2e-wtp->m2e-WTP</mapping>
							</mappings>
							<favicon>https://raw.githubusercontent.com/eclipse-m2e/m2e-wtp/refs/heads/master/org.eclipse.m2e.wtp/m2e-wtp_icon_32px.png</favicon>
							<bodyImage>https://raw.githubusercontent.com/eclipse-m2e/m2e-wtp/refs/heads/master/org.eclipse.m2e.wtp/m2e-wtp_icon_32px.png</bodyImage>
							<titleImage>https://raw.githubusercontent.com/eclipse-m2e/m2e-core/refs/heads/main/assets/m2e_Logo_plain.svg</titleImage>
							<bree>true</bree>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
